#-*- coding:ISO-8859-1 -*-
#Form implementation generated from reading ui file 'src/interface.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.setEnabled(True)
		MainWindow.resize(1234, 639)
		MainWindow.setWindowOpacity(1.0)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
		self.gridLayout.setObjectName("gridLayout")
		self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
		self.tabWidget.setMaximumSize(QtCore.QSize(16777212, 16777215))
		self.tabWidget.setObjectName("tabWidget")
		self.tab = QtWidgets.QWidget()
		self.tab.setObjectName("tab")
		self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
		self.gridLayout_4.setObjectName("gridLayout_4")
		self.TableResultados = QtWidgets.QTableWidget(self.tab)
		self.TableResultados.setAutoScrollMargin(16)
		self.TableResultados.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
		self.TableResultados.setGridStyle(QtCore.Qt.DotLine)
		self.TableResultados.setObjectName("TableResultados")
		self.TableResultados.setColumnCount(6)
		self.TableResultados.setRowCount(0)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		font = QtGui.QFont()
		font.setPointSize(11)
		item.setFont(font)
		self.TableResultados.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		font = QtGui.QFont()
		font.setPointSize(11)
		item.setFont(font)
		self.TableResultados.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		font = QtGui.QFont()
		font.setPointSize(11)
		item.setFont(font)
		self.TableResultados.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		font = QtGui.QFont()
		font.setPointSize(11)
		item.setFont(font)
		self.TableResultados.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		font = QtGui.QFont()
		font.setPointSize(11)
		item.setFont(font)
		self.TableResultados.setHorizontalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		font = QtGui.QFont()
		font.setPointSize(11)
		font.setBold(False)
		font.setWeight(50)
		item.setFont(font)
		self.TableResultados.setHorizontalHeaderItem(5, item)
		self.TableResultados.horizontalHeader().setDefaultSectionSize(135)
		self.TableResultados.horizontalHeader().setHighlightSections(False)
		self.TableResultados.verticalHeader().setVisible(False)
		self.TableResultados.verticalHeader().setHighlightSections(False)
		self.gridLayout_4.addWidget(self.TableResultados, 0, 0, 1, 1)
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.pushButtonLimpar = QtWidgets.QPushButton(self.tab)
		self.pushButtonLimpar.setEnabled(False)
		font = QtGui.QFont()
		font.setPointSize(8)
		self.pushButtonLimpar.setFont(font)
		self.pushButtonLimpar.setDefault(False)
		self.pushButtonLimpar.setObjectName("pushButtonLimpar")
		self.horizontalLayout.addWidget(self.pushButtonLimpar)
		self.pushButtonSalvar = QtWidgets.QPushButton(self.tab)
		self.pushButtonSalvar.setEnabled(False)
		self.pushButtonSalvar.setObjectName("pushButtonSalvar")
		self.horizontalLayout.addWidget(self.pushButtonSalvar)
		self.pushButtonCancelarSimulacao = QtWidgets.QPushButton(self.tab)
		self.pushButtonCancelarSimulacao.setEnabled(False)
		self.pushButtonCancelarSimulacao.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.pushButtonCancelarSimulacao.setFlat(False)
		self.pushButtonCancelarSimulacao.setObjectName("pushButtonCancelarSimulacao")
		self.horizontalLayout.addWidget(self.pushButtonCancelarSimulacao)
		self.label = QtWidgets.QLabel(self.tab)
		font = QtGui.QFont()
		font.setPointSize(8)
		font.setBold(False)
		font.setWeight(50)
		self.label.setFont(font)
		self.label.setObjectName("label")
		self.horizontalLayout.addWidget(self.label)
		self.progressBarSimulacao = QtWidgets.QProgressBar(self.tab)
		self.progressBarSimulacao.setEnabled(True)
		self.progressBarSimulacao.setProperty("value", 0)
		self.progressBarSimulacao.setTextVisible(True)
		self.progressBarSimulacao.setOrientation(QtCore.Qt.Horizontal)
		self.progressBarSimulacao.setObjectName("progressBarSimulacao")
		self.horizontalLayout.addWidget(self.progressBarSimulacao)
		self.gridLayout_4.addLayout(self.horizontalLayout, 2, 0, 1, 1)
		self.ProgressoTorneiosAnterioresWidget = QtWidgets.QWidget(self.tab)
		self.ProgressoTorneiosAnterioresWidget.setEnabled(True)
		self.ProgressoTorneiosAnterioresWidget.setGeometry(QtCore.QRect(50, 310, 671, 61))
		self.ProgressoTorneiosAnterioresWidget.setObjectName("ProgressoTorneiosAnterioresWidget")
		self.tabWidget.addTab(self.tab, "")
		self.tab_2 = QtWidgets.QWidget()
		self.tab_2.setObjectName("tab_2")
		self.tabWidget.addTab(self.tab_2, "")
		self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
		self.toolBox = QtWidgets.QToolBox(self.centralwidget)
		self.toolBox.setMaximumSize(QtCore.QSize(400, 16777215))
		self.toolBox.setObjectName("toolBox")
		self.NovoTorneio = QtWidgets.QWidget()
		self.NovoTorneio.setGeometry(QtCore.QRect(0, 0, 400, 510))
		self.NovoTorneio.setObjectName("NovoTorneio")
		self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.NovoTorneio)
		self.verticalLayout_9.setObjectName("verticalLayout_9")
		self.widget_2 = QtWidgets.QWidget(self.NovoTorneio)
		self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
		self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
		self.widget_2.setObjectName("widget_2")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
		self.verticalLayout.setSpacing(7)
		self.verticalLayout.setObjectName("verticalLayout")
		self.comboBoxFiltro1 = QtWidgets.QComboBox(self.widget_2)
		self.comboBoxFiltro1.setObjectName("comboBoxFiltro1")
		self.comboBoxFiltro1.addItem("")
		self.comboBoxFiltro1.addItem("")
		self.comboBoxFiltro1.addItem("")
		self.verticalLayout.addWidget(self.comboBoxFiltro1, 0, QtCore.Qt.AlignTop)
		self.comboBoxFiltro2 = QtWidgets.QComboBox(self.widget_2)
		self.comboBoxFiltro2.setEnabled(False)
		self.comboBoxFiltro2.setObjectName("comboBoxFiltro2")
		self.verticalLayout.addWidget(self.comboBoxFiltro2, 0, QtCore.Qt.AlignTop)
		self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_14.setObjectName("horizontalLayout_14")
		self.listWidgetEstrategias = QtWidgets.QListWidget(self.widget_2)
		self.listWidgetEstrategias.setMaximumSize(QtCore.QSize(16777215, 16777215))
		self.listWidgetEstrategias.setObjectName("listWidgetEstrategias")
		self.horizontalLayout_14.addWidget(self.listWidgetEstrategias)
		self.widget = QtWidgets.QWidget(self.widget_2)
		self.widget.setMaximumSize(QtCore.QSize(16777215, 100))
		self.widget.setObjectName("widget")
		self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
		self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_3.setSpacing(1)
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.pushButtonAdicionarEstrategia = QtWidgets.QPushButton(self.widget)
		self.pushButtonAdicionarEstrategia.setMaximumSize(QtCore.QSize(35, 23))
		self.pushButtonAdicionarEstrategia.setObjectName("pushButtonAdicionarEstrategia")
		self.verticalLayout_3.addWidget(self.pushButtonAdicionarEstrategia)
		self.pushButtonRemoverEstrategia = QtWidgets.QPushButton(self.widget)
		self.pushButtonRemoverEstrategia.setEnabled(True)
		self.pushButtonRemoverEstrategia.setMaximumSize(QtCore.QSize(35, 23))
		self.pushButtonRemoverEstrategia.setObjectName("pushButtonRemoverEstrategia")
		self.verticalLayout_3.addWidget(self.pushButtonRemoverEstrategia)
		self.horizontalLayout_14.addWidget(self.widget)
		self.listWidgetEstrategiasSelecionadas = QtWidgets.QListWidget(self.widget_2)
		self.listWidgetEstrategiasSelecionadas.setMaximumSize(QtCore.QSize(16777215, 16777215))
		self.listWidgetEstrategiasSelecionadas.setObjectName("listWidgetEstrategiasSelecionadas")
		self.horizontalLayout_14.addWidget(self.listWidgetEstrategiasSelecionadas)
		self.verticalLayout.addLayout(self.horizontalLayout_14)
		self.verticalLayout_9.addWidget(self.widget_2)
		self.widgetPersonalizarConfiguracoes1 = QtWidgets.QWidget(self.NovoTorneio)
		self.widgetPersonalizarConfiguracoes1.setEnabled(True)
		self.widgetPersonalizarConfiguracoes1.setMinimumSize(QtCore.QSize(0, 0))
		self.widgetPersonalizarConfiguracoes1.setMaximumSize(QtCore.QSize(16777215, 155))
		self.widgetPersonalizarConfiguracoes1.setObjectName("widgetPersonalizarConfiguracoes1")
		self.gridLayout_2 = QtWidgets.QGridLayout(self.widgetPersonalizarConfiguracoes1)
		self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
		self.gridLayout_2.setHorizontalSpacing(1)
		self.gridLayout_2.setVerticalSpacing(5)
		self.gridLayout_2.setObjectName("gridLayout_2")
		self.widget_4 = QtWidgets.QWidget(self.widgetPersonalizarConfiguracoes1)
		self.widget_4.setObjectName("widget_4")
		self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
		self.horizontalLayout_4.setContentsMargins(0, 0, -1, 0)
		self.horizontalLayout_4.setSpacing(0)
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		self.widget_6 = QtWidgets.QWidget(self.widget_4)
		self.widget_6.setMaximumSize(QtCore.QSize(80, 16777215))
		self.widget_6.setObjectName("widget_6")
		self.gridLayout_13 = QtWidgets.QGridLayout(self.widget_6)
		self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
		self.gridLayout_13.setObjectName("gridLayout_13")
		self.verticalLayout_5 = QtWidgets.QVBoxLayout()
		self.verticalLayout_5.setContentsMargins(-1, -1, -1, 33)
		self.verticalLayout_5.setSpacing(30)
		self.verticalLayout_5.setObjectName("verticalLayout_5")
		self.labelTurnos1 = QtWidgets.QLabel(self.widget_6)
		self.labelTurnos1.setMaximumSize(QtCore.QSize(16777215, 16777215))
		font = QtGui.QFont()
		font.setPointSize(11)
		font.setBold(True)
		font.setWeight(75)
		self.labelTurnos1.setFont(font)
		self.labelTurnos1.setInputMethodHints(QtCore.Qt.ImhNone)
		self.labelTurnos1.setAlignment(QtCore.Qt.AlignCenter)
		self.labelTurnos1.setObjectName("labelTurnos1")
		self.verticalLayout_5.addWidget(self.labelTurnos1)
		self.spinBoxTurnos1 = QtWidgets.QSpinBox(self.widget_6)
		self.spinBoxTurnos1.setMaximumSize(QtCore.QSize(75, 20))
		self.spinBoxTurnos1.setToolTip("")
		self.spinBoxTurnos1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.spinBoxTurnos1.setMinimum(1)
		self.spinBoxTurnos1.setMaximum(1000000000)
		self.spinBoxTurnos1.setProperty("value", 200)
		self.spinBoxTurnos1.setObjectName("spinBoxTurnos1")
		self.verticalLayout_5.addWidget(self.spinBoxTurnos1)
		self.gridLayout_13.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
		self.horizontalLayout_4.addWidget(self.widget_6)
		self.line_3 = QtWidgets.QFrame(self.widget_4)
		self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_3.setObjectName("line_3")
		self.horizontalLayout_4.addWidget(self.line_3)
		self.verticalLayout_8 = QtWidgets.QVBoxLayout()
		self.verticalLayout_8.setObjectName("verticalLayout_8")
		self.labelPayoff1 = QtWidgets.QLabel(self.widget_4)
		self.labelPayoff1.setMaximumSize(QtCore.QSize(16777215, 16777215))
		font = QtGui.QFont()
		font.setPointSize(11)
		font.setBold(True)
		font.setWeight(75)
		self.labelPayoff1.setFont(font)
		self.labelPayoff1.setScaledContents(False)
		self.labelPayoff1.setAlignment(QtCore.Qt.AlignCenter)
		self.labelPayoff1.setObjectName("labelPayoff1")
		self.verticalLayout_8.addWidget(self.labelPayoff1)
		self.gridLayout_9 = QtWidgets.QGridLayout()
		self.gridLayout_9.setVerticalSpacing(5)
		self.gridLayout_9.setObjectName("gridLayout_9")
		self.spinBoxR1 = QtWidgets.QDoubleSpinBox(self.widget_4)
		self.spinBoxR1.setMaximumSize(QtCore.QSize(60, 16777215))
		self.spinBoxR1.setMaximum(1000.0)
		self.spinBoxR1.setProperty("value", 3.0)
		self.spinBoxR1.setObjectName("spinBoxR1")
		self.gridLayout_9.addWidget(self.spinBoxR1, 1, 1, 1, 1)
		self.spinBoxS1 = QtWidgets.QDoubleSpinBox(self.widget_4)
		self.spinBoxS1.setMaximumSize(QtCore.QSize(60, 16777215))
		self.spinBoxS1.setMaximum(1000.0)
		self.spinBoxS1.setObjectName("spinBoxS1")
		self.gridLayout_9.addWidget(self.spinBoxS1, 3, 1, 1, 1)
		self.spinBoxT1 = QtWidgets.QDoubleSpinBox(self.widget_4)
		self.spinBoxT1.setMaximumSize(QtCore.QSize(60, 16777215))
		self.spinBoxT1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
		self.spinBoxT1.setMouseTracking(False)
		self.spinBoxT1.setToolTip("")
		self.spinBoxT1.setWhatsThis("")
		self.spinBoxT1.setProperty("showGroupSeparator", False)
		self.spinBoxT1.setDecimals(2)
		self.spinBoxT1.setMinimum(0.0)
		self.spinBoxT1.setMaximum(1000.0)
		self.spinBoxT1.setProperty("value", 5.0)
		self.spinBoxT1.setObjectName("spinBoxT1")
		self.gridLayout_9.addWidget(self.spinBoxT1, 1, 0, 1, 1)
		self.labelP1 = QtWidgets.QLabel(self.widget_4)
		self.labelP1.setMaximumSize(QtCore.QSize(16777215, 15))
		font = QtGui.QFont()
		font.setPointSize(8)
		self.labelP1.setFont(font)
		self.labelP1.setToolTip("")
		self.labelP1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
		self.labelP1.setObjectName("labelP1")
		self.gridLayout_9.addWidget(self.labelP1, 2, 0, 1, 1)
		self.spinBoxP1 = QtWidgets.QDoubleSpinBox(self.widget_4)
		self.spinBoxP1.setMaximumSize(QtCore.QSize(60, 16777215))
		self.spinBoxP1.setPrefix("")
		self.spinBoxP1.setMaximum(1000.0)
		self.spinBoxP1.setProperty("value", 1.0)
		self.spinBoxP1.setObjectName("spinBoxP1")
		self.gridLayout_9.addWidget(self.spinBoxP1, 3, 0, 1, 1)
		self.labelT1 = QtWidgets.QLabel(self.widget_4)
		self.labelT1.setMaximumSize(QtCore.QSize(16777215, 15))
		font = QtGui.QFont()
		font.setPointSize(8)
		self.labelT1.setFont(font)
		self.labelT1.setToolTip("")
		self.labelT1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
		self.labelT1.setObjectName("labelT1")
		self.gridLayout_9.addWidget(self.labelT1, 0, 0, 1, 1)
		self.labelS1 = QtWidgets.QLabel(self.widget_4)
		self.labelS1.setMaximumSize(QtCore.QSize(16777215, 15))
		font = QtGui.QFont()
		font.setPointSize(8)
		self.labelS1.setFont(font)
		self.labelS1.setToolTip("")
		self.labelS1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
		self.labelS1.setObjectName("labelS1")
		self.gridLayout_9.addWidget(self.labelS1, 2, 1, 1, 1)
		self.labelR1 = QtWidgets.QLabel(self.widget_4)
		self.labelR1.setMaximumSize(QtCore.QSize(16777215, 15))
		font = QtGui.QFont()
		font.setPointSize(8)
		self.labelR1.setFont(font)
		self.labelR1.setToolTip("")
		self.labelR1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
		self.labelR1.setObjectName("labelR1")
		self.gridLayout_9.addWidget(self.labelR1, 0, 1, 1, 1)
		self.verticalLayout_8.addLayout(self.gridLayout_9)
		self.horizontalLayout_4.addLayout(self.verticalLayout_8)
		self.gridLayout_2.addWidget(self.widget_4, 3, 2, 1, 1)
		self.labelPersonalizarConfiguracoes1 = QtWidgets.QLabel(self.widgetPersonalizarConfiguracoes1)
		self.labelPersonalizarConfiguracoes1.setEnabled(True)
		self.labelPersonalizarConfiguracoes1.setMaximumSize(QtCore.QSize(16777215, 19))
		font = QtGui.QFont()
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		self.labelPersonalizarConfiguracoes1.setFont(font)
		self.labelPersonalizarConfiguracoes1.setLineWidth(1)
		self.labelPersonalizarConfiguracoes1.setTextFormat(QtCore.Qt.AutoText)
		self.labelPersonalizarConfiguracoes1.setAlignment(QtCore.Qt.AlignCenter)
		self.labelPersonalizarConfiguracoes1.setObjectName("labelPersonalizarConfiguracoes1")
		self.gridLayout_2.addWidget(self.labelPersonalizarConfiguracoes1, 1, 2, 1, 1)
		self.line_25 = QtWidgets.QFrame(self.widgetPersonalizarConfiguracoes1)
		self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_25.setObjectName("line_25")
		self.gridLayout_2.addWidget(self.line_25, 2, 2, 1, 1)
		self.line_30 = QtWidgets.QFrame(self.widgetPersonalizarConfiguracoes1)
		self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_30.setObjectName("line_30")
		self.gridLayout_2.addWidget(self.line_30, 4, 2, 1, 1)
		self.line_10 = QtWidgets.QFrame(self.widgetPersonalizarConfiguracoes1)
		self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_10.setObjectName("line_10")
		self.gridLayout_2.addWidget(self.line_10, 3, 3, 1, 1)
		self.line_26 = QtWidgets.QFrame(self.widgetPersonalizarConfiguracoes1)
		self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_26.setObjectName("line_26")
		self.gridLayout_2.addWidget(self.line_26, 0, 2, 1, 1)
		self.line_5 = QtWidgets.QFrame(self.widgetPersonalizarConfiguracoes1)
		self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_5.setObjectName("line_5")
		self.gridLayout_2.addWidget(self.line_5, 3, 0, 1, 1)
		self.verticalLayout_9.addWidget(self.widgetPersonalizarConfiguracoes1)
		self.pushButtonIniciarTorneioPersonalizado = QtWidgets.QPushButton(self.NovoTorneio)
		self.pushButtonIniciarTorneioPersonalizado.setEnabled(False)
		self.pushButtonIniciarTorneioPersonalizado.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.pushButtonIniciarTorneioPersonalizado.setObjectName("pushButtonIniciarTorneioPersonalizado")
		self.verticalLayout_9.addWidget(self.pushButtonIniciarTorneioPersonalizado)
		self.toolBox.addItem(self.NovoTorneio, "")
		self.TorneiosAnteriores = QtWidgets.QWidget()
		self.TorneiosAnteriores.setGeometry(QtCore.QRect(0, 0, 400, 510))
		self.TorneiosAnteriores.setObjectName("TorneiosAnteriores")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.TorneiosAnteriores)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.comboBoxSelecionarTorneio = QtWidgets.QComboBox(self.TorneiosAnteriores)
		self.comboBoxSelecionarTorneio.setMaximumSize(QtCore.QSize(380, 16777215))
		self.comboBoxSelecionarTorneio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.comboBoxSelecionarTorneio.setToolTip("")
		self.comboBoxSelecionarTorneio.setObjectName("comboBoxSelecionarTorneio")
		self.comboBoxSelecionarTorneio.addItem("")
		self.comboBoxSelecionarTorneio.addItem("")
		self.comboBoxSelecionarTorneio.addItem("")
		self.comboBoxSelecionarTorneio.addItem("")
		self.comboBoxSelecionarTorneio.addItem("")
		self.comboBoxSelecionarTorneio.addItem("")
		self.verticalLayout_2.addWidget(self.comboBoxSelecionarTorneio, 0, QtCore.Qt.AlignTop)
		self.widgetPersonalizarConfiguracoes2 = QtWidgets.QWidget(self.TorneiosAnteriores)
		self.widgetPersonalizarConfiguracoes2.setEnabled(True)
		self.widgetPersonalizarConfiguracoes2.setMinimumSize(QtCore.QSize(0, 350))
		self.widgetPersonalizarConfiguracoes2.setMaximumSize(QtCore.QSize(380, 233))
		self.widgetPersonalizarConfiguracoes2.setObjectName("widgetPersonalizarConfiguracoes2")
		self.gridLayout_10 = QtWidgets.QGridLayout(self.widgetPersonalizarConfiguracoes2)
		self.gridLayout_10.setContentsMargins(-1, -1, -1, 9)
		self.gridLayout_10.setObjectName("gridLayout_10")
		self.verticalLayout_4 = QtWidgets.QVBoxLayout()
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.line_2 = QtWidgets.QFrame(self.widgetPersonalizarConfiguracoes2)
		self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_2.setObjectName("line_2")
		self.verticalLayout_4.addWidget(self.line_2)
		self.labelPersonalizarConfiguracoes2 = QtWidgets.QLabel(self.widgetPersonalizarConfiguracoes2)
		self.labelPersonalizarConfiguracoes2.setEnabled(True)
		self.labelPersonalizarConfiguracoes2.setMaximumSize(QtCore.QSize(16777215, 40))
		font = QtGui.QFont()
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		self.labelPersonalizarConfiguracoes2.setFont(font)
		self.labelPersonalizarConfiguracoes2.setLineWidth(1)
		self.labelPersonalizarConfiguracoes2.setTextFormat(QtCore.Qt.AutoText)
		self.labelPersonalizarConfiguracoes2.setAlignment(QtCore.Qt.AlignCenter)
		self.labelPersonalizarConfiguracoes2.setObjectName("labelPersonalizarConfiguracoes2")
		self.verticalLayout_4.addWidget(self.labelPersonalizarConfiguracoes2)
		self.line_7 = QtWidgets.QFrame(self.widgetPersonalizarConfiguracoes2)
		self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_7.setObjectName("line_7")
		self.verticalLayout_4.addWidget(self.line_7)
		self.widget_7 = QtWidgets.QWidget(self.widgetPersonalizarConfiguracoes2)
		self.widget_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
		self.widget_7.setObjectName("widget_7")
		self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_7)
		self.horizontalLayout_5.setObjectName("horizontalLayout_5")
		self.line_6 = QtWidgets.QFrame(self.widget_7)
		self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_6.setObjectName("line_6")
		self.horizontalLayout_5.addWidget(self.line_6)
		self.widgetQuantidadeInteracoes2 = QtWidgets.QWidget(self.widget_7)
		self.widgetQuantidadeInteracoes2.setObjectName("widgetQuantidadeInteracoes2")
		self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widgetQuantidadeInteracoes2)
		self.verticalLayout_6.setObjectName("verticalLayout_6")
		self.labelQuantidadeInteracoes2 = QtWidgets.QLabel(self.widgetQuantidadeInteracoes2)
		self.labelQuantidadeInteracoes2.setMinimumSize(QtCore.QSize(0, 125))
		self.labelQuantidadeInteracoes2.setMaximumSize(QtCore.QSize(16777215, 100))
		font = QtGui.QFont()
		font.setPointSize(11)
		font.setBold(True)
		font.setWeight(75)
		self.labelQuantidadeInteracoes2.setFont(font)
		self.labelQuantidadeInteracoes2.setInputMethodHints(QtCore.Qt.ImhNone)
		self.labelQuantidadeInteracoes2.setAlignment(QtCore.Qt.AlignCenter)
		self.labelQuantidadeInteracoes2.setObjectName("labelQuantidadeInteracoes2")
		self.verticalLayout_6.addWidget(self.labelQuantidadeInteracoes2, 0, QtCore.Qt.AlignTop)
		self.spinBoxQuantidadeInteracoest2 = QtWidgets.QSpinBox(self.widgetQuantidadeInteracoes2)
		self.spinBoxQuantidadeInteracoest2.setEnabled(True)
		self.spinBoxQuantidadeInteracoest2.setMaximumSize(QtCore.QSize(75, 16777215))
		self.spinBoxQuantidadeInteracoest2.setToolTip("")
		self.spinBoxQuantidadeInteracoest2.setMinimum(1)
		self.spinBoxQuantidadeInteracoest2.setMaximum(1000000000)
		self.spinBoxQuantidadeInteracoest2.setProperty("value", 30000)
		self.spinBoxQuantidadeInteracoest2.setObjectName("spinBoxQuantidadeInteracoest2")
		self.verticalLayout_6.addWidget(self.spinBoxQuantidadeInteracoest2, 0, QtCore.Qt.AlignHCenter)
		self.horizontalLayout_5.addWidget(self.widgetQuantidadeInteracoes2, 0, QtCore.Qt.AlignVCenter)
		self.line_4 = QtWidgets.QFrame(self.widget_7)
		self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_4.setObjectName("line_4")
		self.horizontalLayout_5.addWidget(self.line_4)
		self.widgetPayoff2 = QtWidgets.QWidget(self.widget_7)
		self.widgetPayoff2.setObjectName("widgetPayoff2")
		self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widgetPayoff2)
		self.verticalLayout_7.setObjectName("verticalLayout_7")
		self.labelPayoff2 = QtWidgets.QLabel(self.widgetPayoff2)
		self.labelPayoff2.setMinimumSize(QtCore.QSize(0, 50))
		self.labelPayoff2.setMaximumSize(QtCore.QSize(16777215, 50))
		font = QtGui.QFont()
		font.setPointSize(11)
		font.setBold(True)
		font.setWeight(75)
		self.labelPayoff2.setFont(font)
		self.labelPayoff2.setScaledContents(False)
		self.labelPayoff2.setAlignment(QtCore.Qt.AlignCenter)
		self.labelPayoff2.setWordWrap(True)
		self.labelPayoff2.setObjectName("labelPayoff2")
		self.verticalLayout_7.addWidget(self.labelPayoff2)
		self.widget_3 = QtWidgets.QWidget(self.widgetPayoff2)
		self.widget_3.setMinimumSize(QtCore.QSize(160, 110))
		self.widget_3.setObjectName("widget_3")
		self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_3)
		self.gridLayout_6.setObjectName("gridLayout_6")
		self.gridLayout_5 = QtWidgets.QGridLayout()
		self.gridLayout_5.setVerticalSpacing(6)
		self.gridLayout_5.setObjectName("gridLayout_5")
		self.labelS2 = QtWidgets.QLabel(self.widget_3)
		self.labelS2.setMaximumSize(QtCore.QSize(16777215, 15))
		font = QtGui.QFont()
		font.setPointSize(8)
		self.labelS2.setFont(font)
		self.labelS2.setToolTip("")
		self.labelS2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
		self.labelS2.setObjectName("labelS2")
		self.gridLayout_5.addWidget(self.labelS2, 2, 1, 1, 1)
		self.labelP2 = QtWidgets.QLabel(self.widget_3)
		self.labelP2.setMaximumSize(QtCore.QSize(16777215, 15))
		font = QtGui.QFont()
		font.setPointSize(8)
		self.labelP2.setFont(font)
		self.labelP2.setToolTip("")
		self.labelP2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
		self.labelP2.setObjectName("labelP2")
		self.gridLayout_5.addWidget(self.labelP2, 2, 0, 1, 1)
		self.labelR2 = QtWidgets.QLabel(self.widget_3)
		self.labelR2.setMaximumSize(QtCore.QSize(16777215, 15))
		font = QtGui.QFont()
		font.setPointSize(8)
		self.labelR2.setFont(font)
		self.labelR2.setToolTip("")
		self.labelR2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
		self.labelR2.setObjectName("labelR2")
		self.gridLayout_5.addWidget(self.labelR2, 0, 1, 1, 1)
		self.spinBoxR2 = QtWidgets.QDoubleSpinBox(self.widget_3)
		self.spinBoxR2.setMaximumSize(QtCore.QSize(60, 16777215))
		self.spinBoxR2.setMaximum(1000.0)
		self.spinBoxR2.setProperty("value", 3.0)
		self.spinBoxR2.setObjectName("spinBoxR2")
		self.gridLayout_5.addWidget(self.spinBoxR2, 1, 1, 1, 1)
		self.spinBoxP2 = QtWidgets.QDoubleSpinBox(self.widget_3)
		self.spinBoxP2.setMaximumSize(QtCore.QSize(60, 16777215))
		self.spinBoxP2.setPrefix("")
		self.spinBoxP2.setMaximum(1000.0)
		self.spinBoxP2.setProperty("value", 1.0)
		self.spinBoxP2.setObjectName("spinBoxP2")
		self.gridLayout_5.addWidget(self.spinBoxP2, 3, 0, 1, 1)
		self.labelT2 = QtWidgets.QLabel(self.widget_3)
		self.labelT2.setMaximumSize(QtCore.QSize(16777215, 15))
		font = QtGui.QFont()
		font.setPointSize(8)
		self.labelT2.setFont(font)
		self.labelT2.setToolTip("")
		self.labelT2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
		self.labelT2.setObjectName("labelT2")
		self.gridLayout_5.addWidget(self.labelT2, 0, 0, 1, 1)
		self.spinBoxS2 = QtWidgets.QDoubleSpinBox(self.widget_3)
		self.spinBoxS2.setMaximumSize(QtCore.QSize(60, 16777215))
		self.spinBoxS2.setMaximum(1000.0)
		self.spinBoxS2.setObjectName("spinBoxS2")
		self.gridLayout_5.addWidget(self.spinBoxS2, 3, 1, 1, 1)
		self.spinBoxT2 = QtWidgets.QDoubleSpinBox(self.widget_3)
		self.spinBoxT2.setMaximumSize(QtCore.QSize(60, 16777215))
		self.spinBoxT2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
		self.spinBoxT2.setMouseTracking(False)
		self.spinBoxT2.setToolTip("")
		self.spinBoxT2.setWhatsThis("")
		self.spinBoxT2.setProperty("showGroupSeparator", False)
		self.spinBoxT2.setDecimals(2)
		self.spinBoxT2.setMinimum(0.0)
		self.spinBoxT2.setMaximum(1000.0)
		self.spinBoxT2.setProperty("value", 5.0)
		self.spinBoxT2.setObjectName("spinBoxT2")
		self.gridLayout_5.addWidget(self.spinBoxT2, 1, 0, 1, 1)
		self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
		self.verticalLayout_7.addWidget(self.widget_3)
		self.line = QtWidgets.QFrame(self.widgetPayoff2)
		self.line.setFrameShape(QtWidgets.QFrame.HLine)
		self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line.setObjectName("line")
		self.verticalLayout_7.addWidget(self.line)
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.labelTurnos2 = QtWidgets.QLabel(self.widgetPayoff2)
		self.labelTurnos2.setMaximumSize(QtCore.QSize(16777215, 20))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(True)
		font.setWeight(75)
		self.labelTurnos2.setFont(font)
		self.labelTurnos2.setInputMethodHints(QtCore.Qt.ImhNone)
		self.labelTurnos2.setAlignment(QtCore.Qt.AlignCenter)
		self.labelTurnos2.setObjectName("labelTurnos2")
		self.horizontalLayout_2.addWidget(self.labelTurnos2, 0, QtCore.Qt.AlignHCenter)
		self.spinBoxTurnos2 = QtWidgets.QSpinBox(self.widgetPayoff2)
		self.spinBoxTurnos2.setMaximumSize(QtCore.QSize(75, 16777215))
		self.spinBoxTurnos2.setToolTip("")
		self.spinBoxTurnos2.setMinimum(1)
		self.spinBoxTurnos2.setMaximum(1000000000)
		self.spinBoxTurnos2.setProperty("value", 200)
		self.spinBoxTurnos2.setObjectName("spinBoxTurnos2")
		self.horizontalLayout_2.addWidget(self.spinBoxTurnos2, 0, QtCore.Qt.AlignHCenter)
		self.verticalLayout_7.addLayout(self.horizontalLayout_2)
		self.horizontalLayout_5.addWidget(self.widgetPayoff2, 0, QtCore.Qt.AlignVCenter)
		self.line_8 = QtWidgets.QFrame(self.widget_7)
		self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
		self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_8.setObjectName("line_8")
		self.horizontalLayout_5.addWidget(self.line_8)
		self.verticalLayout_4.addWidget(self.widget_7)
		self.pushButtonSimularTorneio2 = QtWidgets.QPushButton(self.widgetPersonalizarConfiguracoes2)
		self.pushButtonSimularTorneio2.setEnabled(True)
		self.pushButtonSimularTorneio2.setMaximumSize(QtCore.QSize(120, 16777215))
		self.pushButtonSimularTorneio2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.pushButtonSimularTorneio2.setObjectName("pushButtonSimularTorneio2")
		self.verticalLayout_4.addWidget(self.pushButtonSimularTorneio2, 0, QtCore.Qt.AlignHCenter)
		self.gridLayout_10.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
		self.verticalLayout_2.addWidget(self.widgetPersonalizarConfiguracoes2, 0, QtCore.Qt.AlignTop)
		self.toolBox.addItem(self.TorneiosAnteriores, "")
		self.gridLayout.addWidget(self.toolBox, 0, 0, 1, 1)
		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 1234, 26))
		self.menubar.setObjectName("menubar")
		self.menuSair = QtWidgets.QMenu(self.menubar)
		self.menuSair.setObjectName("menuSair")
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)
		self.actionSair = QtWidgets.QAction(MainWindow)
		self.actionSair.setObjectName("actionSair")
		self.menuSair.addAction(self.actionSair)
		self.menubar.addAction(self.menuSair.menuAction())

		self.retranslateUi(MainWindow)
		self.tabWidget.setCurrentIndex(0)
		self.toolBox.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "Ferramenta Addario"))
		item = self.TableResultados.horizontalHeaderItem(0)
		item.setText(_translate("MainWindow", "Rank"))
		item.setToolTip(_translate("MainWindow", "Classificação da estratégia"))
		item = self.TableResultados.horizontalHeaderItem(1)
		item.setText(_translate("MainWindow", "Estratégia"))
		item.setToolTip(_translate("MainWindow", "Nome da estratégia"))
		item = self.TableResultados.horizontalHeaderItem(2)
		item.setText(_translate("MainWindow", "GanhoTotal"))
		item.setToolTip(_translate("MainWindow", "Ganho total obtido pela estratégia"))
		item = self.TableResultados.horizontalHeaderItem(3)
		item.setText(_translate("MainWindow", "Ganhos/Adversário"))
		item.setToolTip(_translate("MainWindow", "Média de ganhos das interações contra cada adversário"))
		item = self.TableResultados.horizontalHeaderItem(4)
		item.setText(_translate("MainWindow", "Ganhos/Interação"))
		item.setToolTip(_translate("MainWindow", "Média de ganhos por cada interação que a estratégia participou"))
		item = self.TableResultados.horizontalHeaderItem(5)
		item.setText(_translate("MainWindow", "Interações"))
		item.setToolTip(_translate("MainWindow", "Quantidade total de interações que a estratégia participou"))
		self.pushButtonLimpar.setToolTip(_translate("MainWindow", "Limpar Resultados"))
		self.pushButtonLimpar.setText(_translate("MainWindow", "Limpar"))
		self.pushButtonLimpar.setShortcut(_translate("MainWindow", "Ctrl+L"))
		self.pushButtonSalvar.setText(_translate("MainWindow", "Salvar"))
		self.pushButtonSalvar.setShortcut(_translate("MainWindow", "Ctrl+S"))
		self.pushButtonCancelarSimulacao.setText(_translate("MainWindow", "Cancelar"))
		self.pushButtonCancelarSimulacao.setShortcut(_translate("MainWindow", "Ctrl+X"))
		self.label.setText(_translate("MainWindow", "Progresso"))
		self.progressBarSimulacao.setToolTip(_translate("MainWindow", "Progresso da Simulação"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Resultado em Dados"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Informações"))
		self.comboBoxFiltro1.setItemText(0, _translate("MainWindow", "Selecionar Filtro"))
		self.comboBoxFiltro1.setItemText(1, _translate("MainWindow", "Por Torneios"))
		self.comboBoxFiltro1.setItemText(2, _translate("MainWindow", "Por Classificação Addario"))
		self.pushButtonAdicionarEstrategia.setText(_translate("MainWindow", "++"))
		self.pushButtonAdicionarEstrategia.setShortcut(_translate("MainWindow", "Right"))
		self.pushButtonRemoverEstrategia.setText(_translate("MainWindow", "--"))
		self.pushButtonRemoverEstrategia.setShortcut(_translate("MainWindow", "Left"))
		self.labelTurnos1.setToolTip(_translate("MainWindow", "Quantidade de rodadas em uma interação"))
		self.labelTurnos1.setText(_translate("MainWindow", "Turnos"))
		self.labelPayoff1.setToolTip(_translate("MainWindow", "Tabela de Pagamentos dos torneios RoundRobin"))
		self.labelPayoff1.setText(_translate("MainWindow", "Tabela de Pagamento"))
		self.labelP1.setText(_translate("MainWindow", "Punishment"))
		self.labelT1.setText(_translate("MainWindow", "Temptation"))
		self.labelS1.setText(_translate("MainWindow", "Sucker"))
		self.labelR1.setText(_translate("MainWindow", "Reward"))
		self.labelPersonalizarConfiguracoes1.setToolTip(_translate("MainWindow", "Configurações acessíveis ao torneio selecionado"))
		self.labelPersonalizarConfiguracoes1.setText(_translate("MainWindow", "Personalizar Configurações"))
		self.pushButtonIniciarTorneioPersonalizado.setText(_translate("MainWindow", "Iniciar Simulação"))
		self.toolBox.setItemText(self.toolBox.indexOf(self.NovoTorneio), _translate("MainWindow", "Criar Novo Torneio "))
		self.comboBoxSelecionarTorneio.setItemText(0, _translate("MainWindow", "Selecione o Torneio"))
		self.comboBoxSelecionarTorneio.setItemText(1, _translate("MainWindow", "Primeiro Torneio de Axelrod"))
		self.comboBoxSelecionarTorneio.setItemText(2, _translate("MainWindow", "Segundo Torneio de Axelrod"))
		self.comboBoxSelecionarTorneio.setItemText(3, _translate("MainWindow", "Torneio de Aniversário de 20 anos"))
		self.comboBoxSelecionarTorneio.setItemText(4, _translate("MainWindow", "Torneio Knight"))
		self.comboBoxSelecionarTorneio.setItemText(5, _translate("MainWindow", "Torneio Nebuloso de Borges"))
		self.labelPersonalizarConfiguracoes2.setToolTip(_translate("MainWindow", "Configurações acessíveis ao torneio selecionado"))
		self.labelPersonalizarConfiguracoes2.setText(_translate("MainWindow", "Personalizar Configurações"))
		self.labelQuantidadeInteracoes2.setToolTip(_translate("MainWindow", "Quantidade de interações por grupo no torneio de Borges"))
		self.labelQuantidadeInteracoes2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Quantidade</p><p align=\"center\">de</p><p align=\"center\">Interações</p></body></html>"))
		self.labelPayoff2.setToolTip(_translate("MainWindow", "Tabela de Pagamentos dos torneios RoundRobin"))
		self.labelPayoff2.setText(_translate("MainWindow", "Tabela de Pagamento"))
		self.labelS2.setText(_translate("MainWindow", "Sucker"))
		self.labelP2.setText(_translate("MainWindow", "Punishment"))
		self.labelR2.setText(_translate("MainWindow", "Reward"))
		self.labelT2.setText(_translate("MainWindow", "Temptation"))
		self.labelTurnos2.setToolTip(_translate("MainWindow", "Quantidade de rodadas em uma interação"))
		self.labelTurnos2.setText(_translate("MainWindow", "Turnos"))
		self.pushButtonSimularTorneio2.setText(_translate("MainWindow", "Iniciar Simulação"))
		self.toolBox.setItemText(self.toolBox.indexOf(self.TorneiosAnteriores), _translate("MainWindow", "Torneios Anteriores"))
		self.menuSair.setTitle(_translate("MainWindow", "Opções"))
		self.actionSair.setText(_translate("MainWindow", "Sair"))
		self.actionSair.setShortcut(_translate("MainWindow", "Esc"))
